/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariationsRouteImport } from './routes/variations'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlatingRouteImport } from './routes/plating'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookingRouteImport } from './routes/cooking'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'

const VariationsRoute = VariationsRouteImport.update({
  id: '/variations',
  path: '/variations',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatingRoute = PlatingRouteImport.update({
  id: '/plating',
  path: '/plating',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookingRoute = CookingRouteImport.update({
  id: '/cooking',
  path: '/cooking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/plating': typeof PlatingRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/variations': typeof VariationsRoute
  '/recipes/$id': typeof RecipesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/plating': typeof PlatingRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/variations': typeof VariationsRoute
  '/recipes/$id': typeof RecipesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cooking': typeof CookingRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/plating': typeof PlatingRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/variations': typeof VariationsRoute
  '/recipes/$id': typeof RecipesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cooking'
    | '/login'
    | '/nutrition'
    | '/plating'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/signup'
    | '/variations'
    | '/recipes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cooking'
    | '/login'
    | '/nutrition'
    | '/plating'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/signup'
    | '/variations'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/cooking'
    | '/login'
    | '/nutrition'
    | '/plating'
    | '/profile'
    | '/recipes'
    | '/scan'
    | '/signup'
    | '/variations'
    | '/recipes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookingRoute: typeof CookingRoute
  LoginRoute: typeof LoginRoute
  NutritionRoute: typeof NutritionRoute
  PlatingRoute: typeof PlatingRoute
  ProfileRoute: typeof ProfileRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  ScanRoute: typeof ScanRoute
  SignupRoute: typeof SignupRoute
  VariationsRoute: typeof VariationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variations': {
      id: '/variations'
      path: '/variations'
      fullPath: '/variations'
      preLoaderRoute: typeof VariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plating': {
      id: '/plating'
      path: '/plating'
      fullPath: '/plating'
      preLoaderRoute: typeof PlatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cooking': {
      id: '/cooking'
      path: '/cooking'
      fullPath: '/cooking'
      preLoaderRoute: typeof CookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof RecipesRoute
    }
  }
}

interface RecipesRouteChildren {
  RecipesIdRoute: typeof RecipesIdRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesIdRoute: RecipesIdRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookingRoute: CookingRoute,
  LoginRoute: LoginRoute,
  NutritionRoute: NutritionRoute,
  PlatingRoute: PlatingRoute,
  ProfileRoute: ProfileRoute,
  RecipesRoute: RecipesRouteWithChildren,
  ScanRoute: ScanRoute,
  SignupRoute: SignupRoute,
  VariationsRoute: VariationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
